### ISSUE TITLE
Handle accounts passed as a string

### ISSUE THREAD

**Issue by robert-nash** [drkane/ixbrl-parse#10]
In my use of this helpful library I have found it useful to pass strings directly to IXBRL instead of a file handler. In my case this was for handling files loaded using requests from a URL. I wonder if this is something which could be useful more widely?

My quick way of achieving this was to modify the __init__ function of the IXBRL as below however this may well not be the best way for general usage.

`def __init__(self, f=None, content=None):
        if f:
            self.soup = BeautifulSoup(f.read(), "xml")
        elif content:
            self.soup = BeautifulSoup(content, "xml")
        else:
            raise AttributeError
        self._get_schema()
        self._get_contexts()
        self._get_units()
        self._get_nonnumeric()
        self._get_numeric()`

**Comment by drkane** [comment]
Hi @robert-nash - great to hear the library is helpful.

You might find it easier to use the `io` library to wrap your string and then pass it to the IXBRL class. `io.StringIO` will wrap a string and turn it into something that works like a file - all `IXBRL` needs is something with a `.read()` method.

```python
import io
from ixbrlparse import IXBRL

content = '''<some ixbrl content>'''
x = IXBRL(io.StringIO(content))
```

(NB I haven't tried this code but something similar should work.)

**Comment by robert-nash** [comment]
That sounds like a good solution to the problem. Thank you for bringing this to my attention.
