### ISSUE TITLE
Unconverted Data remains

### ISSUE THREAD

**Issue by Besarion-95** [drkane/ixbrl-parse#12]
Hi Dr Kane,

Ive been continuing testing different runs through and found this error. 
Seems to be related to when the program tries to pull the date out of a specific kind of account: "Unaudited Financial Statements".

Its raised here:
core.py: "enddate": s.find(['xbrli:endDate', 'endDate']).text if s.find(['xbrli:endDate', 'endDate']) else None

Then to:
context.py: startdate, "%Y-%m-%d").date() if startdate else None

Ending in:
_strptime.py: tt, fraction, gmtoff_fraction = _strptime(data_string, format)
if len(data_string) != found.end():
    361         raise ValueError("unconverted data remains: %s" %
--> 362                           data_string[found.end():])
[Unconverted-Data.zip](https://github.com/drkane/ixbrl-parse/files/4301544/Unconverted-Data.zip)

Hope you've been well.

**Comment by drkane** [comment]
Thanks for the report. Lookis like there's a rogue blank space at the end of the datestring.

Should be fixed by e78afd1f2ebe3c927c549adf54f10b078434f05b
