### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' - Solution

### ISSUE THREAD

**Issue by Besarion-95** [drkane/ixbrl-parse#13]
Hi David,

Found an error on line 49 of core.py. "AttributeError: 'NoneType' object has no attribute 'get' ". 
The below code does return the correct schema I just haven't figured out how to integrate it into Core.py 

Hope your doing well considering all the Corona virus stuff,

with open(filename, "r") as f:
    soup = BeautifulSoup(f, 'html.parser')
    resources = soup.find(['ix:references', 'references'])
    #print(resources)
    for s in resources.find_all(['link:schemaRef', 'schemaRef', 'schemaref', 'link:schemaref']):
        x = s.get('xlink:href')
        print(x)
[ErrorFolder.zip](https://github.com/drkane/ixbrl-parse/files/4330673/ErrorFolder.zip)

**Comment by Besarion-95** [comment]
I am guessing something like this but this raises the same error:
```
        resources = self.soup.find(['ix:references', 'references'])
        for s in resources.find_all(['link:schemaRef', 'schemaRef', 'schemaref', 'link:schemaref']):
            self.schema = s.get('xlink:href')
```

**Comment by drkane** [comment]
This is because the files are in `us-ascii` encoding and beautifulsoup assumes it's in utf. You can instead pass the file in binary form and it'll work - eg `with open(filename, "rb") as f:`. I've changed the default options to use this.

**Comment by sreekarn** [comment]
Even by using this open(filename, "rb") as f: I'm getting the same error AttributeError: 'NoneType' object has no attribute 'get'

**Comment by drkane** [comment]
> 
> 
> Even by using this open(filename, "rb") as f: I'm getting the same error AttributeError: 'NoneType' object has no attribute 'get'

Hi @sreekarn  - thanks for reporting the error. Is it possible to share a file that causes it so I can look into it further?
