### ISSUE TITLE
NotImplementedError: Format "num-dot-decimal" not implemented (namespace "ixt")

### ISSUE THREAD

**Issue by Bixi81** [drkane/ixbrl-parse#16]
Hi,

this is really a great package. I tried to parse some iXBLR myself, but seeing all your work it becomes clear that this is quite some work. So thanks for the package!

I have an issue. I try to parse some iXBLR annual report from "Gleif": https://www.gleif.org/content/1-about/10-governance/11-annual-report/gleif-annual-report-2019.zip

When I try to parse it, I get the error below. I tried to dig into the source files, but I could not locate the actual problem or find out how to solve the error. 

Would be glad to hear back from you, Cheers!

 File "...\python\gleif_try.py", line 8, in <module>
    x = IXBRL(a)
  File "C:\Python3\lib\site-packages\ixbrlparse\core.py", line 16, in __init__
    self._get_numeric()
  File "C:\Python3\lib\site-packages\ixbrlparse\core.py", line 97, in _get_numeric
    ixbrlNumeric(element)
  File "C:\Python3\lib\site-packages\ixbrlparse\components\numeric.py", line 34, in __init__
    self.format = get_format(format_['format_'])(**format_)
  File "C:\Python3\lib\site-packages\ixbrlparse\components\transform.py", line 92, in get_format
    namespace,
NotImplementedError: Format "num-dot-decimal" not implemented (namespace "ixt")

**Comment by drkane** [comment]
Hi @Bixi81  - thanks for reporting the issue.

I think I've solved this one in 2ba2cecefcddd3c5f7c5c3bd2ea2d8a6d57179fd - it should now remove any dashes when checking the format to use (so `num-dot-decimal` should become `numdotdecimal`). I've added a test for this here: https://github.com/drkane/ixbrl-parse/blob/2ba2cecefcddd3c5f7c5c3bd2ea2d8a6d57179fd/tests/test_classes.py#L126

If you upgrade the pip package to 1.1.2 it should be fixed.

**Comment by Bixi81** [comment]
Hi @drkane: Thanks for the reply, great you could fix this... As per docs (https://www.xbrl.org/Specification/inlineXBRL-transformationRegistry/REC-2015-02-26/inlineXBRL-transformationRegistry-REC-2015-02-26.html#sec-ixt-24) there should be no dash but some reports seem to use a dash in the format definition.
