### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by Besarion-95** [drkane/ixbrl-parse#7]
Hi there Ive been trying to fix the issue. When i ran some tests i came across this error: 
AttributeError: 'NoneType' object has no attribute 'attrs'

in the following section:
ixbrl-parse-master\ixbrlparse\core.py
22(line)  for k in self.soup.find('html').attrs:
24(line)  if k.startswith("xmlns") or ":" in k:
25(line) self.namespaces[k] = self.soup.find('html')[k].split(" ")

Tried using a try-except to avoid NoneType exception:
but that hasnt worked.

Ill let you know if i find a fix.

**Comment by Besarion-95** [comment]
Seems to be

**Comment by Besarion-95** [comment]
This this the company causing the issue. It seems to be using a dormant style even though its listed as active. https://beta.companieshouse.gov.uk/company/01578171/filing-history
What i think is happening is that it doesnt see this: <link:schemaRef xlink:arcrole="http://www.w3.org/1999/xlink/properties/linkbase" xlink:href="http://www.companieshouse.gov.uk/ef/xbrl/uk/fr/gaap/ae/2009-06-21/uk-gaap-ae-2009-06-21.xsd" xlink:type="simple"/> in the HTML.

**Comment by drkane** [comment]
Thanks for sharing the issue - I've added a test case for this type of account. Looks like I might need to rethink how the XML parsing works. They've used a different (but presumably valid) way of specifying the namespace for the XML tags.

**Comment by drkane** [comment]
I've reworked the code to use a different parser - let me know if it fixes your issue @Besarion-95

**Comment by Besarion-95** [comment]
Hi drkane, 

Thank you for time sadly it hasnt fixed it. Still get the same error message

**Comment by Besarion-95** [comment]
Hi there drkane, 

Thank you that has fixed the issue.
